name: R18 Generator List

on:
  schedule:
    - cron: "0 0 */15 * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run parser
        run: node index.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin main
          git checkout main
          git add data/R18Anime.css
          git add data/R18Manga.css
          git diff --cached --quiet && exit 0
          git commit -m "Update Censorship List"
          git push